#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx git-format-staged -f 'prettier --ignore-unknown --stdin-filepath "{}"' "*"
npx git-format-staged --no-write -f 'eslint --stdin --stdin-filename "{}" >&2' "*.js" "*.ts"
