import {resolve} from "path";
import {PRNGSeed} from "@pkmn/sim";
import {ExperienceConfig} from "../../../config/types";
import {ModelWorker} from "../../model/worker";
import {ThreadPool} from "../../pool";
import {SimResult} from "../sim/playGame";
import {
    GameAgentConfig,
    GameProtocol,
    GameWorkerData,
} from "./worker/GameProtocol";
import {GameWorker} from "./worker/GameWorker";

/** Args for {@link GamePool.addGame}. */
export interface GamePoolArgs {
    /** Unique identifier for logging. */
    readonly id: number;
    /** Config for the models that will play against each other. */
    readonly agents: readonly [GamePoolAgentConfig, GamePoolAgentConfig];
    /** Used to request model ports for the game workers. */
    readonly models: ModelWorker;
    /** Args for starting the game. */
    readonly play: PlayArgs;
}

/** Config for {@link GamePool.addGame} agents. */
export type GamePoolAgentConfig = GameAgentConfig<false /*TWithModelPort*/>;

/** Args for starting a game. */
export interface PlayArgs {
    /**
     * Maximum amount of turns until the game is considered a tie. Games can go
     * on forever if this is not set and both agents only decide to switch.
     */
    readonly maxTurns?: number;
    /** Path to the file to store logs in. */
    readonly logPath?: string;
    /** Seed for the battle PRNG. */
    readonly seed?: PRNGSeed;
    /**
     * Configuration to process any Experiences that get generated by agents. If
     * omitted, experience is discarded.
     */
    readonly experienceConfig?: ExperienceConfig;
}

/** {@link GamePool} stream output type. */
export interface GamePoolResult extends SimResult {
    /** Unique identifier for logging. */
    readonly id: number;
    /** Number of TrainingExamples that were saved, if enabled. */
    numExamples?: number;
}

/** Path to the GameWorker script. */
const workerScriptPath = resolve(__dirname, "worker", "worker.js");

/** Uses a thread pool to dispatch parallel games. */
export class GamePool {
    /** Number of threads in the thread pool. */
    public get numThreads(): number {
        return this.pool.numThreads;
    }

    /** Wrapped thread pool for managing game workers. */
    private readonly pool: ThreadPool<
        GameWorker,
        GameProtocol,
        keyof GameProtocol,
        GameWorkerData
    >;

    /**
     * Creates a GamePool.
     *
     * @param numThreads Number of workers to create.
     * @param getExpPath Optional getter function for experience files. Called
     * once per worker.
     */
    public constructor(numThreads: number, getExpPath?: () => Promise<string>) {
        this.pool = new ThreadPool(
            numThreads,
            workerScriptPath,
            GameWorker,
            async () => ({expPath: await getExpPath?.()}) /*workerData*/,
        );
    }

    /**
     * Queues a game to be played.
     *
     * @param args Game args.
     * @param callback Called when a worker has been assigned to the game.
     * @returns A Promise to get the results of the game. Also returns any
     * errors.
     */
    public async addGame(
        args: GamePoolArgs,
        callback?: () => void,
    ): Promise<GamePoolResult> {
        // Grab a free worker.
        const port = await this.pool.takePort();

        try {
            callback?.();
            return await port.playGame(args);
        } catch (e) {
            return {id: args.id, err: e as Error};
        } finally {
            this.pool.givePort(port);
        }
    }

    /** Closes the thread pool. */
    public async close(): Promise<void> {
        return await this.pool.close();
    }
}
